### ISSUE TITLE
Activity Feed Refresh - displays "Targets" when being set, but NOT for activities logged iOS

### ISSUE THREAD

**Issue by robwynj** [jiscdev/la-app#32]
When setting targets, the activity feed shows that activity pretty much immediately - when logging an activity (using Activity Log - Log Recent) it does not show in the Activity Feed in the same way/ time. I have also "pulled down" the activity field list (to refresh) and this doesn't make a difference. Will need investigation.

**Comment by TherapyBox** [comment]
Not able to replicate, it's showing up immediately for me? Can you provide steps?

**Comment by robwynj** [comment]
Hia,

Can you double-check - it (an activity being logged) appears immediately in the "activity log" but not in the "activity feed" - should this be the case?

Kind Regards

Rob

**Comment by robwynj** [comment]
Also, should a target being reached by shown in the activity feed - I just wanted to double-check! Same check goes for a trophy being displayed. @michaelwebbjisc any thoughts? Just checking scope.

**Comment by TherapyBox** [comment]
Hi, sorry missed these comments. I think this is within the original scope. The idea is that rather than display individual incidents of reports, the app counts up how much of a certain activity you've done over longer periods of time (I think we're doing calculations for 1 day, 2 days, 3 days, 5 days and a week) and these get displayed on the feed rather than each report, which we were concerned could become overkill. Trophies, targets and meeting both of those are considered reasonably rare incidents, which is why they appear in the feed.
