### ISSUE TITLE
Should display Assignment Name

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/la-app#9]
This might be both and API change and client change, so marked for all three as enhancement

**Comment by robwynj** [comment]
ASSESS_TYPE_NAME

@TB - will need to confirm sending this via the API (and you pick it out from there, as additional detail passed to the app)

ACTION - @TB & @petros @leebaylis to confer & resolve

**Comment by petros** [comment]
@robwynj why are you mentioning me in this project?

**Comment by TherapyBox** [comment]
If you make this change, we shouldn't have any problems implementing.

**Comment by TherapyBox** [comment]
We've implemented the ASSESS_TYPE_NAME with fallback on X_MOD_NAME, so that the app will still not seem broken in this section. As long as one of these keys exists, the Attainment section will work fine, with priority for ASSESS_TYPE_NAME.

so display will show Date -- Assessment or Module Name (assement name given priority) -- Mark.

Is this okay?

**Comment by michaelwebbjisc** [comment]
Tested and working as expected.
